# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/lib/i3blocks/$BLOCK_NAME
separator_block_width=20
separator=false
markup=none

# Generic media player support
#
# This displays "ARTIST - SONG" if a music is playing.
# Supported players are: spotify, vlc, audacious, xmms2, mplayer, and others.
[mediaplayer]
instance=spotify
interval=5
signal=10
command=/home/mateusz/repos/linux_scripts/i3blocks/i3blocks-contrib/mediaplayer/mediaplayer
color=#3399ff

# Volume indicator
#
# The first parameter sets the step (and units to display)
# The second parameter overrides the mixer selection
# See the script for details.
[volume]
color=#3399ff
command=/home/mateusz/repos/linux_scripts/i3blocks/scripts/volume.sh
markup=pango
interval=1
signal=1

# Memory usage
#
# The type defaults to "mem" if the instance is not specified.
[memory]
color=#3399ff
interval=1
separator=false
command=/home/mateusz/repos/linux_scripts/i3blocks/scripts/ram.sh
markup=pango

## CPU Usage
#
[cpu]
color=#3399ff
interval=1
separator=false
command=/home/mateusz/repos/linux_scripts/i3blocks/scripts/cpu.sh
markup=pango


# Network interface monitoring
#
# If the instance is not specified, use the interface used for default route.
# The address can be forced to IPv4 or IPv6 with -4 or -6 switches.


[wifi]
#instance=wlp3s0
color=#3399ff
interval=10
separator=false
command=/home/mateusz/repos/linux_scripts/i3blocks/scripts/wifi.sh
markup=pango

# Battery indicator
#
# The battery instance defaults to 0.
[battery]
color=#3399ff
command=/home/mateusz/repos/linux_scripts/i3blocks/scripts/battery.sh
markup=pango
interval=1

# Date
#
[date]
color=#3399ff
label= 
command=date '+%b %d %a'
interval=5
# Time
#
[time]
color=#ee9940
label= 
command=date '+%H:%M'
interval=5




# OpenVPN support
#
# Support multiple VPN, with colors.
#[openvpn]
#interval=20

# Temperature
#
# Support multiple chips, though lm-sensors.
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
#[temperature]
#label=TEMP
#interval=10

# Key indicators
#
# Add the following bindings to i3 config file:
#
# bindsym --release Caps_Lock exec pkill -SIGRTMIN+11 i3blocks
# bindsym --release Num_Lock  exec pkill -SIGRTMIN+11 i3blocks
#[keyindicator]
#instance=CAPS
#interval=once
#signal=11

#[keyindicator]
#instance=NUM
#interval=once
#signal=11
