#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color "#252525" 
bspc config focused_border_color "#0050b7"
bspc config presel_feedback_color "#89b8f7"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointers true

bspc config external_rules_command ~/.config/bspwm/external_rules

bspc rule -a Firefox desktop='^2' state=tiled

~/scripts/comp &

pgrep bspswallow || ~/.config/bspwm/bspswallow &
~/.config/polybar/launch.sh &
