;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini

[bar/top]
monitor = 

width = 100%
height = 18

wm-restack = bspwm

background = ${colors.background}
foreground = ${colors.foreground}
border-size = 1
separator = |
line-size = 2
line-color = #00000000

spacing = 2
padding-right = 1
module-margin = 1

font-0 = Ubuntu Condensed Nerd Font Complete Mono:size=8;2
font-3 = Font Awesome 5 Free Solid:size=10;2
font-2 = Font Awesome 5 Brands:size=10;2
font-1 = Font Awesome 5 Free:size=10;2
font-4 = Ubuntu Nerd Font Complete:size=8;2

; font-3 = Misc Termsyn.Icons:size=8:antialias=false;0

modules-left = bspwm mpris
modules-center = xwindow
modules-right = cpu memory temperature xbacklight pulseaudio wlan eth battery date powermenu

tray-position = right 
tray-detached = false 
tray-maxsize = 16 
tray-background = ${colors.dark0}
tray-offset-x = 0 
tray-offset-y = 0
tray-padding = 3 
tray-scale = 1.0 

enable-ipc = true

[bar/bottom]
monitor = 

bottom = true
width = 100%
height = 20

wm-restack = bspwm

background = ${colors.background}
foreground = ${colors.foreground}

line-color = #00000000
line-size = 2

border-size = 0 
border-top-size = 0 
border-bottom-size = 2
border-color = #00000000

spacing = 3
padding-right = 0
padding-left = 0
module-margin = 0
module-margin-left = 0
module-margin-right = 6

font-0 = NotoSans-Regular:size=8;0
font-1 = unifont:size=6;1
font-2 = FontAwesome:size=8;-1
font-3 = NotoSans-Regular:size=8;1
font-4 = MaterialIcons:size=10;-1
font-5 = Misc Termsyn:size=8:antialias=false;0
font-6 = DejaVu Sans;size=8;1
font-7 = Icons:size=8;0

modules-left = bspwm mod mpris
modules-center = xwindow
modules-right = temperature memory cpu

tray-position = right 
tray-detached = false 
tray-maxsize = 16 
tray-background = ${colors.dark0}
tray-offset-x = 0 
tray-offset-y = 0
tray-padding = 3 
tray-scale = 1.0 

enable-ipc = true

[settings]
screenchange-reload = true
format-foreground = ${colors.foreground}
format-background = ${colors.background}
